name: apedia_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - albumentations=1.4.*
  - numpy=1.24.*
  - pandas=2.*
  - torch=2.*
  - tqdm=4.*
  - segmentation-models-pytorch=0.3.*
  - matplotlib=3.*
  - cellpose=2.2
  - scikit-image=0.21.*
  - spams=2.6.*
  - staintools=2.1.*
  